# Generated by Django 5.1.6 on 2025-03-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
